FROM porcelani/jdk8-wildfly8

ENV postgres_module_dir=/opt/jboss/wildfly/modules/org/postgresql/main

RUN mkdir -p ${postgres_module_dir}
ADD module.xml ${postgres_module_dir}
ADD postgresql-9.3-1102.jdbc41.jar ${postgres_module_dir}

ENV config_dir=/opt/jboss/wildfly/standalone/configuration
ADD standalone.xml ${config_dir}

ENV deployments_dir=/opt/jboss/wildfly/standalone/deployments
ADD node-info.war ${deployments_dir}


EXPOSE 8080

RUN /opt/jboss/wildfly/bin/add-user.sh admin admin --silent
CMD ["/opt/jboss/wildfly/bin/standalone.sh", "-b", "0.0.0.0", "-bmanagement", "0.0.0.0"]

